title: Abraham Luna # your name (or website title) here
logo: "/images/rsz_c.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Creative Self-Directed Business Analyst with a strong interest in providing digital solutions utilizing
  Data Analytics and Business Intelligence tools. 
  <br><br>
  <a href="https://www.canva.com/design/DAE4LAdBaao/Tb2k_X8ge1R1WMpDvEbgjQ/view?utm_content=DAE4LAdBaao&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/avrahamluna/">View My LinkedIn Profile</a><br><br>
  <a href="https://linktr.ee/avrahamluna">View My Other Links</a>
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
